parameters:
  name: ''
  vmImage: ''
  dependsOn: ''
  pipSettingsScript: setup_pip.yml

jobs:

- job: ${{ parameters.name }}
  dependsOn: ${{ parameters.dependsOn }}

  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - template: ${{ parameters.pipSettingsScript }}

  # currently pip does not correctly install extras on windows for python 3.6
  - script: |
      pip install -e .[test]
    displayName: 'Install dependencies'

  - script: |
      pytest --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  - task: PythonScript@0
    displayName: 'check coverage'
    inputs:
      scriptSource: filePath
      scriptPath: 'zdevelop/azure_scripts/check_coverage.py'
      failOnStderr: true
